package net.laggedhero.revolut.challenge.core.provider

import android.app.Application
import android.content.Context
import net.laggedhero.revolut.challenge.R
import net.laggedhero.revolut.challenge.domain.CurrencyCode

internal class CurrencyStringProviderImpl(application: Application) : CurrencyStringProvider {

    private val context: Context = application.applicationContext

    override fun name(currencyCode: CurrencyCode): String {
        val stringResId = when (currencyCode) {
            is CurrencyCode.AED -> R.string.currency_aed
            is CurrencyCode.AFN -> R.string.currency_afn
            is CurrencyCode.ALL -> R.string.currency_all
            is CurrencyCode.AMD -> R.string.currency_amd
            is CurrencyCode.ANG -> R.string.currency_ang
            is CurrencyCode.AOA -> R.string.currency_aoa
            is CurrencyCode.ARS -> R.string.currency_ars
            is CurrencyCode.AUD -> R.string.currency_aud
            is CurrencyCode.AWG -> R.string.currency_awg
            is CurrencyCode.AZN -> R.string.currency_azn
            is CurrencyCode.BAM -> R.string.currency_bam
            is CurrencyCode.BBD -> R.string.currency_bbd
            is CurrencyCode.BDT -> R.string.currency_bdt
            is CurrencyCode.BGN -> R.string.currency_bgn
            is CurrencyCode.BHD -> R.string.currency_bhd
            is CurrencyCode.BIF -> R.string.currency_bif
            is CurrencyCode.BMD -> R.string.currency_bmd
            is CurrencyCode.BND -> R.string.currency_bnd
            is CurrencyCode.BOB -> R.string.currency_bob
            is CurrencyCode.BOV -> R.string.currency_bov
            is CurrencyCode.BRL -> R.string.currency_brl
            is CurrencyCode.BSD -> R.string.currency_bsd
            is CurrencyCode.BTN -> R.string.currency_btn
            is CurrencyCode.BWP -> R.string.currency_bwp
            is CurrencyCode.BYN -> R.string.currency_byn
            is CurrencyCode.BZD -> R.string.currency_bzd
            is CurrencyCode.CAD -> R.string.currency_cad
            is CurrencyCode.CDF -> R.string.currency_cdf
            is CurrencyCode.CHE -> R.string.currency_che
            is CurrencyCode.CHF -> R.string.currency_chf
            is CurrencyCode.CHW -> R.string.currency_chw
            is CurrencyCode.CLF -> R.string.currency_clf
            is CurrencyCode.CLP -> R.string.currency_clp
            is CurrencyCode.CNY -> R.string.currency_cny
            is CurrencyCode.COP -> R.string.currency_cop
            is CurrencyCode.COU -> R.string.currency_cou
            is CurrencyCode.CRC -> R.string.currency_crc
            is CurrencyCode.CUC -> R.string.currency_cuc
            is CurrencyCode.CUP -> R.string.currency_cup
            is CurrencyCode.CVE -> R.string.currency_cve
            is CurrencyCode.CZK -> R.string.currency_czk
            is CurrencyCode.DJF -> R.string.currency_djf
            is CurrencyCode.DKK -> R.string.currency_dkk
            is CurrencyCode.DOP -> R.string.currency_dop
            is CurrencyCode.DZD -> R.string.currency_dzd
            is CurrencyCode.EGP -> R.string.currency_egp
            is CurrencyCode.ERN -> R.string.currency_ern
            is CurrencyCode.ETB -> R.string.currency_etb
            is CurrencyCode.EUR -> R.string.currency_eur
            is CurrencyCode.FJD -> R.string.currency_fjd
            is CurrencyCode.FKP -> R.string.currency_fkp
            is CurrencyCode.GBP -> R.string.currency_gbp
            is CurrencyCode.GEL -> R.string.currency_gel
            is CurrencyCode.GHS -> R.string.currency_ghs
            is CurrencyCode.GIP -> R.string.currency_gip
            is CurrencyCode.GMD -> R.string.currency_gmd
            is CurrencyCode.GNF -> R.string.currency_gnf
            is CurrencyCode.GTQ -> R.string.currency_gtq
            is CurrencyCode.GYD -> R.string.currency_gyd
            is CurrencyCode.HKD -> R.string.currency_hkd
            is CurrencyCode.HNL -> R.string.currency_hnl
            is CurrencyCode.HRK -> R.string.currency_hrk
            is CurrencyCode.HTG -> R.string.currency_htg
            is CurrencyCode.HUF -> R.string.currency_huf
            is CurrencyCode.IDR -> R.string.currency_idr
            is CurrencyCode.ILS -> R.string.currency_ils
            is CurrencyCode.INR -> R.string.currency_inr
            is CurrencyCode.IQD -> R.string.currency_iqd
            is CurrencyCode.IRR -> R.string.currency_irr
            is CurrencyCode.ISK -> R.string.currency_isk
            is CurrencyCode.JMD -> R.string.currency_jmd
            is CurrencyCode.JOD -> R.string.currency_jod
            is CurrencyCode.JPY -> R.string.currency_jpy
            is CurrencyCode.KES -> R.string.currency_kes
            is CurrencyCode.KGS -> R.string.currency_kgs
            is CurrencyCode.KHR -> R.string.currency_khr
            is CurrencyCode.KMF -> R.string.currency_kmf
            is CurrencyCode.KPW -> R.string.currency_kpw
            is CurrencyCode.KRW -> R.string.currency_krw
            is CurrencyCode.KWD -> R.string.currency_kwd
            is CurrencyCode.KYD -> R.string.currency_kyd
            is CurrencyCode.KZT -> R.string.currency_kzt
            is CurrencyCode.LAK -> R.string.currency_lak
            is CurrencyCode.LBP -> R.string.currency_lbp
            is CurrencyCode.LKR -> R.string.currency_lkr
            is CurrencyCode.LRD -> R.string.currency_lrd
            is CurrencyCode.LSL -> R.string.currency_lsl
            is CurrencyCode.LYD -> R.string.currency_lyd
            is CurrencyCode.MAD -> R.string.currency_mad
            is CurrencyCode.MDL -> R.string.currency_mdl
            is CurrencyCode.MGA -> R.string.currency_mga
            is CurrencyCode.MKD -> R.string.currency_mkd
            is CurrencyCode.MMK -> R.string.currency_mmk
            is CurrencyCode.MNT -> R.string.currency_mnt
            is CurrencyCode.MOP -> R.string.currency_mop
            is CurrencyCode.MRU -> R.string.currency_mru
            is CurrencyCode.MUR -> R.string.currency_mur
            is CurrencyCode.MVR -> R.string.currency_mvr
            is CurrencyCode.MWK -> R.string.currency_mwk
            is CurrencyCode.MXN -> R.string.currency_mxn
            is CurrencyCode.MXV -> R.string.currency_mxv
            is CurrencyCode.MYR -> R.string.currency_myr
            is CurrencyCode.MZN -> R.string.currency_mzn
            is CurrencyCode.NAD -> R.string.currency_nad
            is CurrencyCode.NGN -> R.string.currency_ngn
            is CurrencyCode.NIO -> R.string.currency_nio
            is CurrencyCode.NOK -> R.string.currency_nok
            is CurrencyCode.NPR -> R.string.currency_npr
            is CurrencyCode.NZD -> R.string.currency_nzd
            is CurrencyCode.OMR -> R.string.currency_omr
            is CurrencyCode.PAB -> R.string.currency_pab
            is CurrencyCode.PEN -> R.string.currency_pen
            is CurrencyCode.PGK -> R.string.currency_pgk
            is CurrencyCode.PHP -> R.string.currency_php
            is CurrencyCode.PKR -> R.string.currency_pkr
            is CurrencyCode.PLN -> R.string.currency_pln
            is CurrencyCode.PYG -> R.string.currency_pyg
            is CurrencyCode.QAR -> R.string.currency_qar
            is CurrencyCode.RON -> R.string.currency_ron
            is CurrencyCode.RSD -> R.string.currency_rsd
            is CurrencyCode.RUB -> R.string.currency_rub
            is CurrencyCode.RWF -> R.string.currency_rwf
            is CurrencyCode.SAR -> R.string.currency_sar
            is CurrencyCode.SBD -> R.string.currency_sbd
            is CurrencyCode.SCR -> R.string.currency_scr
            is CurrencyCode.SDG -> R.string.currency_sdg
            is CurrencyCode.SEK -> R.string.currency_sek
            is CurrencyCode.SGD -> R.string.currency_sgd
            is CurrencyCode.SHP -> R.string.currency_shp
            is CurrencyCode.SLL -> R.string.currency_sll
            is CurrencyCode.SOS -> R.string.currency_sos
            is CurrencyCode.SRD -> R.string.currency_srd
            is CurrencyCode.SSP -> R.string.currency_ssp
            is CurrencyCode.STN -> R.string.currency_stn
            is CurrencyCode.SVC -> R.string.currency_svc
            is CurrencyCode.SYP -> R.string.currency_syp
            is CurrencyCode.SZL -> R.string.currency_szl
            is CurrencyCode.THB -> R.string.currency_thb
            is CurrencyCode.TJS -> R.string.currency_tjs
            is CurrencyCode.TMT -> R.string.currency_tmt
            is CurrencyCode.TND -> R.string.currency_tnd
            is CurrencyCode.TOP -> R.string.currency_top
            is CurrencyCode.TRY -> R.string.currency_try
            is CurrencyCode.TTD -> R.string.currency_ttd
            is CurrencyCode.TWD -> R.string.currency_twd
            is CurrencyCode.TZS -> R.string.currency_tzs
            is CurrencyCode.UAH -> R.string.currency_uah
            is CurrencyCode.UGX -> R.string.currency_ugx
            is CurrencyCode.USD -> R.string.currency_usd
            is CurrencyCode.USN -> R.string.currency_usn
            is CurrencyCode.UYI -> R.string.currency_uyi
            is CurrencyCode.UYU -> R.string.currency_uyu
            is CurrencyCode.UZS -> R.string.currency_uzs
            is CurrencyCode.VEF -> R.string.currency_vef
            is CurrencyCode.VND -> R.string.currency_vnd
            is CurrencyCode.VUV -> R.string.currency_vuv
            is CurrencyCode.WST -> R.string.currency_wst
            is CurrencyCode.XAF -> R.string.currency_xaf
            is CurrencyCode.XCD -> R.string.currency_xcd
            is CurrencyCode.XDR -> R.string.currency_xdr
            is CurrencyCode.XOF -> R.string.currency_xof
            is CurrencyCode.XPF -> R.string.currency_xpf
            is CurrencyCode.XSU -> R.string.currency_xsu
            is CurrencyCode.XUA -> R.string.currency_xua
            is CurrencyCode.YER -> R.string.currency_yer
            is CurrencyCode.ZAR -> R.string.currency_zar
            is CurrencyCode.ZMW -> R.string.currency_zmw
            is CurrencyCode.ZWL -> R.string.currency_zwl
        }
        return context.getString(stringResId)
    }
}